name: Deploy PHP App with SonarQube Cloud

on:
  push:
    branches:
      - main  # Trigger deployment on the main branch
  pull_request:
    branches:
      - main  # Trigger for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
         fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} //Sonar Token generated 
         SONAR_HOST_URL: https://sonarcloud.io 
      - name: Print environment variables
        run: echo $SONAR_TOKEN
